/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
module.exports = {
  users: [
    {
      type: 'category',
      label: 'Users guide',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'users', 
        },
      ]
    },
  ],
  developers: [
    {
      type: 'category',
      label: 'Developers guide',
      collapsed: false,
      items: [
        'developers/intro',
      ]

    },
  ],
  docs: [
    {
      type: 'category',
      label: 'Tutoial',
      collapsed: false,
      items: [
        'tuto/intro',
      ]

    },
  ],
  reference: [
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/intro',
        {
          type: 'category',
          label: 'Jmeter',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/jmeter', 
            },
          ]
        },
        {
          type: 'category',
          label: 'Jmeter-plugins',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/jmeter-plugins', 
            },
          ]
        },
      ]
    },
  ],
};
